AuctionsBucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: ${self:custom.AuctionsBucket.name}
    # auctions last one hour; remove images from bucket to lower costs
    LifecycleConfiguration:
      Rules:
        - Id: ExpirePictures
          Status: Enabled
          ExpirationInDays: 1
  
# apply public read policy to bucket  
AuctionsBucketPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
    Bucket: !Ref AuctionsBucket
    PolicyDocument:
      Statement:
        - Sid: PublicRead
          Effect: Allow
          Principal: '*'
          Action:
            - s3:GetObject
          Resource: arn:aws:s3:::${self:custom.AuctionsBucket.name}/*